name: Arqut Tunnel Service
description: Arqut Tunnel Service for Home Assistant
version: 0.1.3
slug: arqut-tunnel
init: false
url: https://github.com/tphan267/tunnel-addon
codenotary: tuan.phan267@gmail.com
webui: http://[HOST]:[PORT:3030]
image: ghcr.io/tphan267/arqut-edge-{arch}:0.1.3
arch:
  - aarch64
  - amd64
map:
  - config:rw
  - share:rw
startup: services
host_network: true
privileged:
  - NET_ADMIN
ports:
  3030/tcp: 3030
ports_description:
  3030/tcp: Used for web interface and API
options:
  data_dir: /data
schema:
  data_dir: str
