name: Build and Push Add-on

on:
  push:
    tags: 'v*' # Trigger on tags like v1.0.1
    branches: [main] # Optional: Also build on main branch
    paths:
      - 'arqut-edge/**'
      - '.github/workflows/build.yaml'
env:
  VERSION: 1.0.1 # Init version

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        arch: [aarch64, amd64]

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from git tag
        if: startsWith(github.ref, 'refs/tags/v')
        id: extract_version
        run: |
          echo "version=${github.ref#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: ./arqut-edge
          platforms: linux/${{ matrix.arch }}
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/arqut-edge-${{ matrix.arch }}:${{ steps.extract_version.outputs.version || env.VERSION }}
            ghcr.io/${{ github.repository_owner }}/arqut-edge-${{ matrix.arch }}:latest
          build-args: |
            BINARY_PATH=./build/${{ matrix.arch }}/arqut-edge
